#!/bin/bash

do_correct=no;
do_force=no;

set -- $(getopt cfh "$@")
while [ $# -gt 0 ]
do
    case "$1" in
    (-c) do_correct=yes;;
    (-f) do_force=yes;;
    (-h) echo "overlay-stack [-c|-f] <overlay_name1> <overlay_name2> ... <rw_overlay_name>";exit 0;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*)  break;;
    esac
    shift
done

if [ "$1" = "" ]; then
	echo "error: overlay_name is missing"
	exit 2
fi

if [ "`id -u`" = "0" ]; then
	echo "$0"
else
	echo "only root mange overlays"
	echo "chande to root and try again"
	exit 0
fi

if [ "$do_correct" = "yes" -a "$do_force" = "yes" ]; then
	echo "overlay-stack [-c|-f] <overlay_name1> <overlay_name2> ... <rw_overlay_name>"
	exit 3
fi

layer_root=""

cat /proc/cmdline | grep mtdblock4 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool1"
fi

cat /proc/cmdline | grep mtdblock5 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool2"
fi

if [ "$layer_root" = "" ]; then
	echo "rootfs not found -> use hack /overlay/layer-rool1"
	layer_root="/overlay/layer-rool1"
fi

# create new layer
cd "$layer_root"
rm -f layer_stack_add_stack ayer_stack_add_stack_tmp

while [ "$1" != "" ]
do
new_overlay="$1"
shift

	if [ -d "$layer_root/$new_overlay" ]; then
		echo "found Layer $layer_root/$new_overlay"
	else
		if [ "$do_correct" = "yes" ]; then
			echo "info: create new Layer $layer_root/$new_overlay"
			mkdir -p "$layer_root/$new_overlay"
		else
			if [ "$do_force" = "no" ]; then
				echo "error: missing Layer $layer_root/$new_overlay"
				exit 1
			else
				echo "info: Layer $layer_root/$new_overlay is not existing"
			fi
		fi
	fi
	cat layer_stack_add_stack > layer_stack_add_stack_tmp
	echo "$layer_root/$new_overlay" > layer_stack_add_stack
	cat layer_stack_add_stack_tmp >> layer_stack_add_stack
done

echo "new config:"
aufs_layers=""
cat layer_stack_add_stack | uniq >layer_stack_new
mv layer_stack_new layer_stack

echo "found: layer_stack"
i=0
while read line
do
	aufs_layers="$aufs_layers:$line"
        if [ $i -eq 0 ]; then
        	echo "$i Layer: $line --> RW-Layer"
                aufs_layers="$aufs_layers=rw"
        else
                echo "$i Layer: $line --> RO-Layer"
                aufs_layers="$aufs_layers=ro"
        fi
                i=`expr $i + 1`;
done < "layer_stack"
echo "$i Layer: / --> RR-Layer"
aufs_layers="$aufs_layers:/=rr"
aufs_mnt_opt="br$aufs_layers"
echo "$aufs_mnt_opt"




	
