#!/bin/bash


if [ "`./test-overlay-list 2>/dev/null | tail -n 1`" = "63d32702ee6417f1e42481c71f8c4913  -" ]; then
                echo "\"test-overlay-list\" ok" 
        else
                echo "\"test-overlay-list\" fail"
                exit 1
fi

if [ "`./test-overlay-list -a 2>/dev/null | tail -n 1`" = "bd5b185139a6cdb8af977b1d32fb5a9d  -" ]; then
		echo "\"test-overlay-list -a\" ok" 
	else
		echo "\"test-overlay-list -a\" fail"
		exit 1 
fi

if [ "`./test-overlay-list -h 2>/dev/null | tail -n 1`" = "overlay-list [-a] [-v] [-h]" ]; then
                echo "\"test-overlay-list -h\" ok" 
        else
                echo "\"test-overlay-list -h\" fail"
                exit 1
fi

if [ "`./test-overlay-list -a -v 2>/dev/null | tail -n 1`" = "fb56a852e06fb24488a0a41e6a9c7fc5  -" ]; then
		echo "\"test-overlay-list -a -v \" ok"
	else
		echo "\"test-overlay-list -a -v \" fail"
		exit 1
fi

if [ "`./test-overlay-list -f 2>/dev/null | tail -n 1`" = "63d32702ee6417f1e42481c71f8c4913  -" ]; then
                echo "\"test-overlay-list -f \" ok"
        else
                echo "\"test-overlay-list -f \" fail"
                exit 1
fi


exit 0

