.. warning::

	These objects, classes, functions and methods are currently UNDOCUMENTED
	(i.e. these are lacking DOC strings)

	module :py:mod:`test_http`

	* :py:mod:`test_http` (C:  1,0: Missing docstring)
	* :py:func:`test_http.TestHTTP` (C: 25,0:TestHTTP: Missing docstring)
	* :py:meth:`test_http.TestHTTP.test_complex` (C: 26,4:TestHTTP.test_complex: Missing docstring)
	* :py:func:`test_http.main` (C: 44,0:main: Missing docstring)

	module :py:mod:`test_samba`

	* :py:mod:`test_samba` (C:  1,0: Missing docstring)
