.. warning::

	These objects, classes, functions and methods are currently UNDOCUMENTED
	(i.e. these are lacking DOC strings)

	module :py:mod:`test_all`

	* :py:func:`test_all.Test` (C: 26,0:Test: Missing docstring)
	* :py:func:`test_all.MyDevice` (C: 48,0:MyDevice: Missing docstring)
	* :py:func:`test_all.main` (C:189,0:main: Missing docstring)

	module :py:mod:`test_http`

	* :py:mod:`test_http` (C:  1,0: Missing docstring)
	* :py:func:`test_http.TestHTTP` (C: 23,0:TestHTTP: Missing docstring)
	* :py:meth:`test_http.TestHTTP.test_complex` (C: 24,4:TestHTTP.test_complex: Missing docstring)
	* :py:func:`test_http.main` (C: 46,0:main: Missing docstring)

	module :py:mod:`test_samba`

	* :py:mod:`test_samba` (C:  1,0: Missing docstring)
	* :py:func:`test_samba.TestSamba` (C: 23,0:TestSamba: Missing docstring)
	* :py:meth:`test_samba.TestSamba.test_complex` (C: 25,4:TestSamba.test_complex: Missing docstring)
	* :py:func:`test_samba.main` (C: 69,0:main: Missing docstring)
