
module :py:mod:`bcc`

* C:144,4:Bcc.hddpower: Missing docstring
* C:168,4:Bcc.heartbeat: Missing docstring
* C:172,0:main: Missing docstring
* C:144,4:Bcc.hddpower: Missing docstring
* C:168,4:Bcc.heartbeat: Missing docstring
* C:172,0:main: Missing docstring

module :py:mod:`serial_conn`

* C:376,4:rst: Missing docstring
* C:376,4:rst: Missing docstring

module :py:mod:`test_all`

* C: 26,0:Test: Missing docstring
* C: 48,0:MyDevice: Missing docstring
* C:191,4:standalone: Missing docstring
* C: 26,0:Test: Missing docstring
* C: 48,0:MyDevice: Missing docstring
* C:191,4:standalone: Missing docstring

module :py:mod:`test_http`

* C:  1,0: Missing docstring
* C: 23,0:TestHTTP: Missing docstring
* C: 24,4:TestHTTP.test_complex: Missing docstring
* C: 46,0:main: Missing docstring
* C:  1,0: Missing docstring
* C: 23,0:TestHTTP: Missing docstring
* C: 24,4:TestHTTP.test_complex: Missing docstring
* C: 46,0:main: Missing docstring

module :py:mod:`test_samba`

* C:  1,0: Missing docstring
* C: 23,0:TestSamba: Missing docstring
* C: 25,4:TestSamba.test_complex: Missing docstring
* C: 69,0:main: Missing docstring
* C:  1,0: Missing docstring
* C: 23,0:TestSamba: Missing docstring
* C: 25,4:TestSamba.test_complex: Missing docstring
* C: 69,0:main: Missing docstring
