#!/bin/bash

if [ "`id -u`" = "0" ]; then
	echo "$0"
else
	echo "only root mange overlays"
	echo "chande to root and try again"
	exit 0
fi

print_all=no;
verbose=no;

set -- $(getopt avh "$@")
while [ $# -gt 0 ]
do
    case "$1" in
    (-a) print_all=yes;;
    (-v) verbose=yes;;
    (-h) echo "overlay-list [-a] [-v] [-h]"; exit 0;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*)  break;;
    esac
    shift
done

layer_root=""

cat /proc/cmdline | grep mtdblock4 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool1"
fi

cat /proc/cmdline | grep mtdblock5 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool2"
fi

if [ -z "$layer_root" ]; then
	echo "error: no rootfs found"
	exit 5
fi

echo "info: Layer root is $layer_root"

# create new layer-root
aufs_layers=""
if [ -d "$layer_root" ]; then
	echo "use: $layer_root"
	cd "$layer_root"
	if [ -e layer_stack ]; then
		echo "found: layer_stack"
		i=0
		for line in $( cat layer_stack );
		do
			aufs_layers="$aufs_layers:$line"
			if [ $i -eq 0 ]; then
				echo "$i Layer: $line --> RW-Layer"
				aufs_layers="$aufs_layers=rw"
			else
				echo "$i Layer: $line --> RO-Layer"
				aufs_layers="$aufs_layers=ro"
			fi
			i=`expr $i + 1`;
		done 
		echo "$i Layer: / --> RR-Layer"
		aufs_layers="$aufs_layers:/=rr"
	else
		echo "create: empty layer_stack"
		echo "0 Layer: / --> RR-Layer"
		aufs_layers="$aufs_layers:/=rr"
		touch layer_stack
	fi

else
	echo "crate: $layer_root"
	mkdir -p $layer_root
	cd "$layer_root"
	echo "create: empty layer_stack"
        echo "0 Layer: / --> RR-Layer"
        aufs_layers="$aufs_layers:/=rr"
	touch layer_stack
fi

aufs_mnt_opt="br$aufs_layers"

echo "$aufs_mnt_opt"

if [ "$print_all" = "yes" ]; then
	echo "other not used layers:"
	cd $layer_root
	layer_all="`ls -d $layer_root/*/ | xargs -l basename`"
	for line in $( echo "$layer_all" );
	do
		found=no
		for stack_line in $( cat layer_stack );
		do
			if [ "$stack_line" = "$layer_root/$line" ]; then
				found=yes
				break;
			fi
		done 
		if [ "$found" != "yes" ]; then
			echo "$layer_root/$line"
		fi
		
	done
fi


