#!/bin/bash

set -- $(getopt nh "$@")
while [ $# -gt 0 ]
do
    case "$1" in
    (-h) echo "overlay-rollback <overlay_name>"; exit 0;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*)  break;;
    esac
    shift
done

rollback_overlay="$1"

if [ "$rollback_overlay" = "" ]; then
	echo "error: mising overlay_name"
	exit 2
fi

if [ "`id -u`" = "0" ]; then
	echo "$0"
else
	echo "only root mange overlays"
	echo "chande to root and try again"
	exit 0
fi


layer_root=""

cat /proc/cmdline | grep mtdblock4 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool1"
fi

cat /proc/cmdline | grep mtdblock5 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool2"
fi

if [ "$layer_root" = "" ]; then
	echo "rootfs not found -> use hack /overlay/layer-rool1"
	layer_root="/overlay/layer-rool1"
fi


cd "$layer_root"

	echo "old_config:"
	aufs_layers=""
	if [ -d $layer_root ]; then
	        echo "use: $layer_root"
        	if [ -e layer_stack ]; then
                	echo "found: layer_stack"
                	i=0
                	while read line
                	do
                        	aufs_layers="$aufs_layers:$line"
                        	if [ $i -eq 0 ]; then
                                	echo "$i Layer: $line --> RW-Layer"
                                	aufs_layers="$aufs_layers=rw"
                        	else
                                	echo "$i Layer: $line --> RO-Layer"
                                	aufs_layers="$aufs_layers=ro"
                        	fi
                        	i=`expr $i + 1`;
                	done < "layer_stack"
                	echo "$i Layer: / --> RR-Layer"
                	aufs_layers="$aufs_layers:/=rr"
        	else
                	echo "create: empty layer_stack"
                	echo "0 Layer: / --> RR-Layer"
                	aufs_layers="$aufs_layers:/=rr"
                	touch layer_stack
        	fi

	else
        	echo "crate: $layer_root"
        	mkdir -p $layer_root
        	cd "$layer_root"
        	echo "create: empty layer_stack"
        	echo "0 Layer: / --> RR-Layer"
        	aufs_layers="$aufs_layers:/=rr"
        	touch layer_stack
	fi
	aufs_layers=""

	echo "new config:"
        echo "found: layer_stack"
	rm -f layer_stack_new
        i=0
	skip=yes
        while read line
        do
		if [ "$skip" = "yes" ]; then
			if [ "$layer_root/$rollback_overlay" = "$line" ]; then
				skip=no
			else
				continue
			fi
		fi
	        aufs_layers="$aufs_layers:$line"
        	if [ $i -eq 0 ]; then
                	echo "$i Layer: $line --> RW-Layer"
                    	aufs_layers="$aufs_layers=rw"
	        else
        	        echo "$i Layer: $line --> RO-Layer"
                        aufs_layers="$aufs_layers=ro"
	        fi
		echo "$line" >>layer_stack_new
                i=`expr $i + 1`;
        done < "layer_stack"
	if [ "$skip" = "yes" ]; then
		echo "error: Layer $rollback_overlay not found"
		exit 4
	fi

	mv layer_stack_new layer_stack
        echo "$i Layer: / --> RR-Layer"
        aufs_layers="$aufs_layers:/=rr"
	aufs_mnt_opt="br$aufs_layers"
	echo "$aufs_mnt_opt"

