#!/bin/bash

do_not_activate=no;

set -- $(getopt nh "$@")
while [ $# -gt 0 ]
do
    case "$1" in
    (-n) do_not_activate=yes;;
    (-h) echo "overlay-add [-n] <new_overlay_name>"; exit 0;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*)  break;;
    esac
    shift
done

new_overlay="$1"

echo "new_overlay=$new_overlay"
echo "do_not_activate=$do_not_activate"

if [ -z "$new_overlay" ]; then
	echo "missing new overlay name"
	exit 2;
fi

if [ "`id -u`" = "0" ]; then
	echo "$0"
else
	echo "only root mange overlays"
	echo "chande to root and try again"
	exit 0
fi

layer_root=""

cat /proc/cmdline | grep mtdblock4 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool1"
fi

cat /proc/cmdline | grep mtdblock5 >/dev/null
if [ "`echo $?`" = "0" ]; then
	layer_root="/overlay/layer-rool2"
fi

# create new layer
if [ -d "$layer_root/$new_overlay" ]; then
	echo "error: Layer $layer_root/$new_overlay is already existing."
	exit 3;
else
	mkdir -p "$layer_root/$new_overlay"
	echo "$?"
fi

if [ "$do_not_activate" = "yes" ]; then
	exit 0;
else
	echo "old_config:"
	aufs_layers=""
	if [ -d $layer_root ]; then
	        echo "use: $layer_root"
        	cd "$layer_root"
        	if [ -e layer_stack ]; then
                	echo "found: layer_stack"
                	i=0
	                for line in $( cat layer_stack );
	                do
                        	aufs_layers="$aufs_layers:$line"
                        	if [ $i -eq 0 ]; then
                                	echo "$i Layer: $line --> RW-Layer"
                                	aufs_layers="$aufs_layers=rw"
                        	else
                                	echo "$i Layer: $line --> RO-Layer"
                                	aufs_layers="$aufs_layers=ro"
                        	fi
                        	i=`expr $i + 1`;
                	done 
                	echo "$i Layer: / --> RR-Layer"
                	aufs_layers="$aufs_layers:/=rr"
        	else
                	echo "create: empty layer_stack"
                	echo "0 Layer: / --> RR-Layer"
                	aufs_layers="$aufs_layers:/=rr"
                	touch layer_stack
        	fi

	else
        	echo "crate: $layer_root"
        	mkdir -p $layer_root
        	cd "$layer_root"
        	echo "create: empty layer_stack"
        	echo "0 Layer: /=rr --> RR-Layer"
        	aufs_layers="$aufs_layers:/=rr"
        	touch layer_stack
	fi
	aufs_layers=""

	echo "new config:"
	layer_stack_add="$layer_root/$new_overlay
`cat layer_stack`"
	echo "$layer_stack_add" | uniq >layer_stack_new
	mv layer_stack_new layer_stack
        echo "found: layer_stack"
        i=0
        for line in $( cat layer_stack );
        do
        	aufs_layers="$aufs_layers:$line"
                if [ $i -eq 0 ]; then
                	echo "$i Layer: $line --> RW-Layer"
                        aufs_layers="$aufs_layers=rw"
                else
                        echo "$i Layer: $line --> RO-Layer"
                        aufs_layers="$aufs_layers=ro"
                fi
                i=`expr $i + 1`;
        done 
        echo "$i Layer: / --> RR-Layer"
        aufs_layers="$aufs_layers:/=rr"
	aufs_mnt_opt="br$aufs_layers"
	echo "$aufs_mnt_opt"
fi 

